### ISSUE TITLE
I can't find the custom permission evaluator

### ISSUE THREAD

**Issue by troyhart** [hotblac/spanners#3]
Your configuration references a custom permission evaluator, but it seems to be missing. The class is: `org.dontpanic.spanners.security.SpannerPermissionEvaluator`

What am I missing?

**Comment by hotblac** [comment]
SpannerPermissionEvaluator was removed in the current major version of the code (4.x) and no references to it exist in the head of the master branch. The SpannerPermissionEvaluator was last present in version 3.5

**Comment by troyhart** [comment]
Thanks!
